### ISSUE TITLE
how to privately publish/upload fba/source to fitbit studio?

### ISSUE THREAD

**Issue by lucifudge** [smirko-dev/fitbit-homeassistant#13]
i read the guide on https://dev.fitbit.com/build/guides/publishing/ but i cannot figure it out.

**Comment by smirko-dev** [comment]
@lucifudge 
Once you copied the whole project (with it's files) to fitbit studio you can build the app (the result is a FBA file).
If you wanna upload it to your device, you need to connect them with the developer menus to your account.
They will appear in fitbit studio and you can then upload your build.
https://dev.fitbit.com/getting-started/

**Comment by smirko-dev** [comment]
Fitbit Studio supports drag&drop, which makes it easy.
Don't forget to create a package.json from my SDK specific templates
