### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by DerJantob** [smirko-dev/fitbit-homeassistant#22]
Hey,
I am unable to connect to my HA. I am running Home Assistant 2023.1.2 and own the Fitbit Sense.
I was able to connect to the api via
`curl -X GET -H "Authorization: Bearer eyJhbdKo..." -H "Content-Type: application/json" http://192.168.178.96:8123/api/`
but HA-Remote always returns a connection error.

App settings:
URL:
http://192.168.178.96
Port:
8123
Token:
eyJhbdKo... and so on

Regards
Jannik

**Comment by smirko-dev** [comment]
The [Fetch API](https://dev.fitbit.com/build/reference/companion-api/fetch/) from FitBit blocks HTTP even though the specification states it should work with local IP's.
They fixed it once, but I also noticed that's not working again.
I opened a topic: https://community.fitbit.com/t5/SDK-Development/Fetch-API-isn-t-working-again-for-local-HTTP-requests/td-p/5331654

**Comment by DerJantob** [comment]
Hm, apparently nothing has happened yet. Kind of a shame that the Fitbit team is ignoring your post.

Oh and one more thing:
I just saw this [Important: Streamlining Fitbit’s Developer Tools](https://community.fitbit.com/t5/SDK-Development/Important-Streamlining-Fitbit-s-Developer-Tools/td-p/5335783). Thought this could maybe affect you

**Comment by smirko-dev** [comment]
I guess they are all busy with Pixel Watch since Google bought Fitbit.
Thx for the hint, I saw the post as well and since all my stuff is on GitHub, I'm fine :)
