### ISSUE TITLE
http (no -s) or nabu casa connectivity

### ISSUE THREAD

**Issue by Xeovar** [smirko-dev/fitbit-homeassistant#24]
Hi,

I just wanted to ask if maybe something has changed over last two years in regard to being able to connect via nabu casa or a local HTTP?
I'd love to use the app, but no way Im gonna do local https, too many complications :(

**Comment by smirko-dev** [comment]
I'm really sorry, but since I never got feedback from Fitbit, I stopped developing the app. I understand the complications about HTTP myself.

**Comment by Xeovar** [comment]
Thanks for the reply, hoped I'll get it somehow to work, but no luck :(
