### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by pyramidak** [smirko-dev/fitbit-homeassistant#4]
1) URL from Nabucasa
2) Port is default 8123
3) generated in HA
4) API activation means in config only: "api:"
correct? Does not work for me.

**Comment by smirko-dev** [comment]
Which app version are you using?
Is your home assistant reachable via HTTPS?
Yes, "api" should be enough.
Did you try to reach the REST api by e.g. `curl -X GET -H "Authorization: Bearer <your_token>" -H "Content-Type: application/json" <your_url>:<your_port>/api/`?

**Comment by pyramidak** [comment]
Then I see problem. Nabu Casa Cloud of Home Assistant providing HTTPS as https://<URL>.ui.nabu.casa without port. 
Trying without PORT the error is curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012).

**Comment by smirko-dev** [comment]
From version 0.4 on the settings menu contains an entry for a specific port.
Does it work now (after adding the port number)?

**Comment by pyramidak** [comment]
Sorry I meant that the nabu casa cloud does not use port. With port the connection does not work. Without port it thow the error.

**Comment by smirko-dev** [comment]
As I read in this thread that nobody really found a solution to get the Rest API  running with nabu casa.
Since my app is based on the Rest API, I also don't see a solution for you. Sorry.

**Comment by pyramidak** [comment]
That´s alright, thank you for trying.

**Comment by D0m3L** [comment]
Hey @pyramidak, just try to set port = 443 as this is the default https port and should also work for a nabu.
So both:
https://(URL).ui.nabu.casa
https://(URL).ui.nabu.casa:443
are in fact the same

**Comment by pyramidak** [comment]
I tried both, not working. Is setting always loaded new before a try? Some applications have extra button to save new setting to watch. I can only hope the new setting is always used. I tried many times. Not working, but the idea was good.

**Comment by smirko-dev** [comment]
Each setting is applied instantly.
