### ISSUE TITLE
Not getting entities showing up.

### ISSUE THREAD

**Issue by chengjwk** [smirko-dev/fitbit-homeassistant#6]
New to fitbit, and no idea how the fitbit environment/API(s) work, but was excited to see your app pop up.

I think I've configured everything correctly:
My settings are:
URL: https://something.duckdns.org
PORT: 443
Token: myrandomlonglivetokenhere
Not sure how to debug, but there's no error just:
`
Home Assistant
N/A
`

I also don't see any errors in my HA logs. I've tried with an internal IP, with/without the port, and with/without the protocol. I've also set up the prequisites in your readme. Honestly haven't looked to deep, so very possible I am missing how it's all wired together, but in `companion/index.js` won't that `Token` always be pulling the hard coded global at the top? 
`
    else if (evt.key === "entities") {
        sendData({key: "clear"});
        JSON.parse(evt.newValue).forEach(element => {
            fetchEntity(address(), Token, element["name"]);
        })
    }
`

**Comment by smirko-dev** [comment]
Hi @chengjwk 
Is your REST Api enabled in your HA instance?
Did you try to reach the REST api by e.g. `curl -X GET -H "Authorization: Bearer <your_token>" -H "Content-Type: application/json" <your_url>:<your_port>/api/`?

**Comment by chengjwk** [comment]
{
  "message": "API running."
}

**Comment by smirko-dev** [comment]
Can you provide a Fitbit log?
Since the REST Api on your HA is working I need to see what happens on the app side.
Please remove private data like the token becausde of I don't need that.

**Comment by chengjwk** [comment]
How can I pull the log off?

Internet acces is enabled. I checked it a couple times. :-P

**Comment by chengjwk** [comment]
I wasn't sure if there was a way to see the logs with the released version so I built and installed the app. I cannot confirm the same error as with the released version as I had to uninstall it, but this time I noticed my token was throwing a 401 (via curl). I created a new one and got the valid respone again. I assume I was missing some characters in my token this time? In your code in the `fetchApiStatus` method:
`
         let data = await response.json();
         if (response.status === 200) {
`
If the response is invalid, the json parsing will fail and obscure the actual error. You probably want:
`
  if(response.ok) {
    let data = await response.json();
`
I didn't play much beyond that to ensure the 401 was surfaced to the user, but the error message might be worth the check, to ensure the user has verified settings.

**Comment by smirko-dev** [comment]
Happy that you found the issue.
Thx for the feedback, I will add your suggestion in the next release (most probably v0.6).

**Comment by chengjwk** [comment]
I'm not sure if this a fitbit sync thing or an app thing... but I retried the release version and got a connection error (on my watch) this time.
I went in (on my phone) and manually clicked all the settings fields and clicked "save" without editting anything as I noticed in the code that those all fired events. After doing that I did manage to connect. 

On a likely unrelated note. When I toggle a switch to "ON". I notice that my light turns on, but the UI does NOT change. When I was debugging I noticed that subsequent taps fired continual "ON" events. I see the sendData call, is it also updating the local button state?

**Comment by smirko-dev** [comment]
As I wrote in the description, I just tested the app with the simulation. I'm happy to get feedback from a real device ^^.
In version 0.5 I added a setting to force UI updates with missing HA response. For SDK4 devices the app update is already approved. Check out the branch `feature/scripts`.

**Comment by chengjwk** [comment]
I'm running a sense, so SDK5. I'm happy to continue testing with a device if it helps. Thanks for the work!

**Comment by blablazzz** [comment]
I have same issue with duckdns and port 443.

**Comment by smirko-dev** [comment]
Hi @blablazzz,
What exactly is your issue? The problem here was a wrong token. The changes, which @chengjwk suggested you can find in branch `feature/bugfixes` and are planned for version 0.6.

**Comment by blablazzz** [comment]
I see only:
Home Assistant
       NA

once opening application of fitbit sense.
I also use https://xxx.duckdns.org
i use port 443
Token - for sure is good, as i was trying to use few different tokens.

And cant connect via fitbit. My Hassio is accessible from local network and
outside. No problems if trying to access it in browser. Cant get it working
on your app.

**Comment by smirko-dev** [comment]
Hi @blablazzz 
Is your REST Api enabled in your HA instance?
Did you try to reach the REST api by e.g. `curl -X GET -H "Authorization: Bearer <your_token>" -H "Content-Type: application/json" <your_url>:<your_port>/api/`?

**Comment by chengjwk** [comment]
That all said, while I have had it working (I just loaded the app on my watch), currently, I am once again seeing Home Assistant N/A on the app, and I also see a:
`Login attempt or request with invalid authentication from` in my dashboard notifications. I don't know if it's the watch, but I don't have any other devices on my network that should be trying to connect. I haven't changed any config in the app. I am running a locally compiled 0.6, but It's not connected, so I don't know if it's doing anything.

**Comment by smirko-dev** [comment]
Hi @chengjwk
1) I will add some notes to the README :).
2) You should see in the logs the token transfered from app (triggered by loading the settings during start) to companion. If it doesn't match your expected token it means with the app something is not working correctly (loading settings maybe).

**Comment by blablazzz** [comment]
yes, i have api: in config file.
Yes, i copied whole token (select all+copy)
Running Curl i get message {"message": "API running."}
 but cant get it work on fitbit.

**Comment by smirko-dev** [comment]
@blablazzz 
Which version are you running? Release or a dev build? In version 0.6, branch `feature/bugfixes`, I show error codes in the UI. This helps to figure out what's going wrong. Either you test that or you need to wait till I release 0.6.

**Comment by blablazzz** [comment]
i run 0.5.1. OK will wait till next release.

**Comment by lucifudge** [comment]
> @blablazzz Which version are you running? Release or a dev build? In version 0.6, branch `feature/bugfixes`, I show error codes in the UI. This helps to figure out what's going wrong. Either you test that or you need to wait till I release 0.6.

same issue here. how do i install dev build for logging feedback?

**Comment by smirko-dev** [comment]
@lucifudge 
Either you build it with Fitbit Studio which can connect to your devices or you wait (maybe till next week) till I release version 0.6.

**Comment by Saviq** [comment]
I reported my findings in the other bug: https://github.com/smirko-dev/fitbit-homeassistant/issues/14#issuecomment-1086608442

**Comment by smirko-dev** [comment]
Close this issue and track this topic with https://github.com/smirko-dev/fitbit-homeassistant/issues/14.
